version: "3.8"

services:
  db:
    image: postgres:15
    container_name: canMaroc_db
    restart: always
    environment:
      POSTGRES_DB: canMaroc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Samir2003@++"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: canMaroc_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_NAME: canMaroc
      DB_USER: postgres
      DB_PASSWORD: "Samir2003@++"
      DB_HOST: db
      PORT: 5000
    volumes:
      - .:/app

volumes:
  db_data:
